CfpConferenceBundle_show_my_cfps:
    pattern:  /cfps
    defaults: { _controller: "CfpConferenceBundle:Cfp:index" }

CfpConferenceBundle_show_cfp:
    pattern:  /cfp/{id}/show
    defaults: { _controller: "CfpConferenceBundle:Cfp:show" }

CfpConferenceBundle_new_cfp:
    pattern:  /cfp/new
    defaults: { _controller: "CfpConferenceBundle:Cfp:new" }

CfpConferenceBundle_create_cfp:
    pattern:  /cfp/create
    defaults: { _controller: "CfpConferenceBundle:Cfp:create" }
    requirements: { _method: post }

CfpConferenceBundle_edit_cfp:
    pattern:  /cfp/{id}/edit
    defaults: { _controller: "CfpConferenceBundle:Cfp:edit" }

CfpConferenceBundle_update_cfp:
    pattern:  /cfp/{id}/update
    defaults: { _controller: "CfpConferenceBundle:Cfp:update" }
    requirements: { _method: post }

CfpConferenceBundle_delete_cfp:
    pattern:  /cfp/{id}/delete
    defaults: { _controller: "CfpConferenceBundle:Cfp:delete" }
    requirements: { _method: post }