CfpCfpBundle_show_my_cfp_talks:
    pattern:  /talks
    defaults: { _controller: "CfpCfpBundle:CfpTalk:index" }

CfpCfpBundle_show_cfp_talk:
    pattern:  /talk/{id}/show
    defaults: { _controller: "CfpCfpBundle:CfpTalk:show" }

CfpCfpBundle_new_cfp_talk:
    pattern:  /talks/new
    defaults: { _controller: "CfpCfpBundle:CfpTalk:new" }

CfpCfpBundle_create_cfp_talk:
    pattern:  /talks/create
    defaults: { _controller: "CfpCfpBundle:CfpTalk:create" }
    requirements: { _method: post }

CfpCfpBundle_edit_cfp_talk:
    pattern:  =/talk/{id}/edit
    defaults: { _controller: "CfpCfpBundle:CfpTalk:edit" }

CfpCfpBundle_update_cfp_talk:
    pattern:  =/talk/{id}/update
    defaults: { _controller: "CfpCfpBundle:CfpTalk:update" }
    requirements: { _method: post }

CfpCfpBundle_delete_cfp_talk:
    pattern:  =/talk/{id}/delete
    defaults: { _controller: "CfpCfpBundle:CfpTalk:delete" }
    requirements: { _method: post }