CfpCfpBundle_show_my_registrations:
    pattern:  /registrations
    defaults: { _controller: "CfpCfpBundle:Registration:index" }

CfpCfpBundle_show_registration:
    pattern:  /registration/{id}/show
    defaults: { _controller: "CfpCfpBundle:Registration:show" }

CfpCfpBundle_new_registration:
    pattern:  /registration/new/{tag}
    defaults: { _controller: "CfpCfpBundle:Registration:new" }

CfpCfpBundle_create_registration:
    pattern:  /registration/create
    defaults: { _controller: "CfpCfpBundle:Registration:create" }
    requirements: { _method: post }

CfpCfpBundle_edit_registration:
    pattern:  /registration/{id}/edit
    defaults: { _controller: "CfpCfpBundle:Registration:edit" }

CfpCfpBundle_update_registration:
    pattern:  /registration/{id}/update
    defaults: { _controller: "CfpCfpBundle:Registration:update" }
    requirements: { _method: post }

CfpCfpBundle_delete_registration:
    pattern:  /registration/{id}/delete
    defaults: { _controller: "CfpCfpBundle:Registration:delete" }
    requirements: { _method: post }