CfpCfpBundle_show_my_submissions:
    pattern:  /submissions
    defaults: { _controller: "CfpCfpBundle:Submission:index" }

CfpCfpBundle_show_submission:
    pattern:  /submission/{submission_id}/show
    defaults: { _controller: "CfpCfpBundle:Submission:show" }

CfpCfpBundle_new_submission:
    pattern:  /submission/new
    defaults: { _controller: "CfpCfpBundle:Submission:new" }

CfpCfpBundle_create_submission:
    pattern:  /submissions/create
    defaults: { _controller: "CfpCfpBundle:Submission:create" }
    requirements: { _method: post }

CfpCfpBundle_edit_submission:
    pattern:  =/submission/{submission_id}/edit
    defaults: { _controller: "CfpCfpBundle:Submission:edit" }

CfpCfpBundle_update_submission:
    pattern:  =/submission/{submission_id}/update
    defaults: { _controller: "CfpCfpBundle:Submission:update" }
    requirements: { _method: post }

CfpCfpBundle_delete_submission:
    pattern:  =/submission/{submission_id}/delete
    defaults: { _controller: "CfpCfpBundle:Submission:delete" }
    requirements: { _method: post }