CfpConferenceBundle_Conferences:
    resource: "@CfpConferenceBundle/Resources/config/routing/conference.yml"
    prefix:   /

CfpConferenceBundle_Admin:
    resource: "@CfpConferenceBundle/Resources/config/routing/admin.yml"
    prefix:   /conference/{tag}

CfpConferenceBundle_Host:
    resource: "@CfpConferenceBundle/Resources/config/routing/host.yml"
    prefix:   /conference/{tag}