parameters:
#    cfp_conference.example.class: Cfp\ConferenceBundle\Example

services:
#    cfp_conference.example:
#        class: %cfp_conference.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    cfp_status.twig.extension:
           class: Cfp\ConferenceBundle\Twig\cfpStatusExtension
           tags:
                -  { name: twig.extension }
    talk.twig.extension:
           class: Cfp\ConferenceBundle\Twig\talkExtension
           tags:
                -  { name: twig.extension }

