CfpPageBundle_homepage:
    pattern:  /
    defaults: { _controller: CfpPageBundle:Default:index }
    requirements:
        _method:  GET

CfpPageBundle_about:
    pattern:  /page/about
    defaults: { _controller: CfpPageBundle:Page:about }
    requirements:
        _method:  GET

CfpPageBundle_contact:
    pattern:  /page/contact
    defaults: { _controller: CfpPageBundle:Page:contact }
    requirements:
        _method:  GET|POST