CfgUserBundle_Talks:
    resource: "@CfpUserBundle/Resources/config/routing/talk.yml"
    prefix:   /my

CfgUserBundle_Biographies:
    resource: "@CfpUserBundle/Resources/config/routing/biography.yml"
    prefix:   /my
