parameters:
#    cfp_user.example.class: Cfp\UserBundle\Example

services:
    talktype:
        class: Cfp\UserBundle\Form\Extension\talkTypeChoiceList
        tags:
            - {name: form.type, alias: talktype}