CfpCfpBundle_Registration:
    resource: "@CfpCfpBundle/Resources/config/routing/registration.yml"
    prefix:   /my

CfpCfpBundle_Submission:
    resource: "@CfpCfpBundle/Resources/config/routing/submission.yml"
    prefix:   /my/registration/{id}